name: CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup venv
        run: uv venv

      - name: Build sdist and wheel
        run: |
          uv build
          uv build --all-packages

      - uses: actions/upload-artifact@v4
        with:
          path: dist

      - name: Install twine
        run: uv pip install twine

      - name: Check products
        run: uv run twine check dist/*

  publish:
    needs: [dist]
    name: Publish to PyPI
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Publish packages
        run: |
          uv publish --all-packages --token ${{ secrets.pypi_password }} --trusted-publishing automatic
